name: brew livecheck bump

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  livecheck-bump:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump outdated formulae
        uses: dawidd6/action-homebrew-bump-formula@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tap: kevin51jiang/tap
          formula: oaicheck
          livecheck: true
